version: '3'

# Define the services (containers) that will be run
services:
  # First service: Flask app
  flask_app:
    # Build the image from the Dockerfile in the parent directory
    build:
      context: ../
      dockerfile: Scores/Dockerfile
    image: eranc/wog_scores_flask
    # Expose the container's port 5000 to host port 8777
    volumes:
      - ./Scores.txt:/app/scores.txt
    ports:
      - "5000:5000"
 # Set environment variables for the container
    environment:
      - FLASK_APP=app/MainScores.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000



